---
swagger: "2.0"
info:
  description: "Endpoints for the Voice Note Service"
  version: "1.0"
  title: "Voice Note API"
host: "localhost:5000"
basePath: "/api/v1"
schemes:
- "http"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /pilots/{pilot_id}/voicenotes:
    get:
      summary: "Retrieve voice notes which are uploaded by specific pilot"
      operationId: "get_retrive_voice_notes_for_specific_pilot"
      parameters:
      - name: "pilot_id"
        in: "path"
        description: "Pilot id"
        required: true
        type: "integer"
      responses:
        200:
          description: "List of voice notes uploaded by specific pilot(Pilot id)"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
    post:
      summary: "Upload new voice note"
      operationId: "post_sending_new_voice_note"
      consumes:
      - "multipart/form-data"
      parameters:
      - name: "pilot_id"
        in: "path"
        description: "Pilot id"
        required: true
        type: "integer"
      - name: "file"
        in: "formData"
        description: "The voice note to upload."
        required: true
        type: "file"
      responses:
        200:
          description: "response with voice note id that had been uploaded"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
  /pilots/{pilot_id}/voicenotes/{voice_note_id}:
    get:
      summary: "Get downloadable link of voice note by pilot id and voice note id"
      operationId: "get_retrive_voice_note_downloadable_url"
      parameters:
      - name: "pilot_id"
        in: "path"
        description: "Pilot id"
        required: true
        type: "integer"
      - name: "voice_note_id"
        in: "path"
        description: "voice note id"
        required: true
        type: "string"
      responses:
        200:
          description: "downloadable link of voice note"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
definitions: {}
