FROM python:3
# Set an environment variable with the directory
ENV FLASK_ENV development
# where we'll be running the app
ENV APP /app
# Create the directory and instruct Docker to operate
# from there from now on
RUN mkdir $APP
WORKDIR $APP
# Expose the port uWSGI will listen on
EXPOSE 5000
# Copy the requirements file in order to install
# Python dependencies
ADD requirements.txt .
ADD .env .
# Install Python dependencies
RUN pip install -r requirements.txt
# We copy the rest of the codebase into the image
ADD . .
# Finally, we run uWSGI with the ini file we
# created earlier
CMD [ "uwsgi", "--ini", "app.ini" ]